# Generated by Django 6.0.3 on 2026-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='ticket_eliminacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='ticket_solicitud',
            field=models.TextField(blank=True, null=True),
        ),
    ]
