# Generated by Django 6.0.3 on 2026-05-02 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0002_alter_extension_observacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceco',
            fields=[
                ('id_ceco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ceco', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'cecos',
            },
        ),
        migrations.CreateModel(
            name='Codigoceco',
            fields=[
                ('id_codigoceco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigoceco', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'codigoscecos',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
