# Generated by Django 6.0.3 on 2026-05-02 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0003_ceco_codigoceco_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoExtension',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=10)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('ASIGNACION', 'ASIGNACION'), ('REASIGNACION', 'REASIGNACION'), ('TRASLADO', 'TRASLADO'), ('LIBERACION', 'LIBERACION')], max_length=20)),
                ('marca', models.CharField(choices=[('REFERENCIA', 'REFERENCIA'), ('CREAR', 'CREAR'), ('ANTERIOR', 'ANTERIOR'), ('TRASLADAR', 'TRASLADAR'), ('LIBERAR', 'LIBERAR')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos_extensiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
