# Generated by Django 6.0.3 on 2026-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0004_movimientoextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoextension',
            name='ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
