# Generated by Django 6.0.3 on 2026-05-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0005_movimientoextension_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoextension',
            name='marca',
            field=models.CharField(choices=[('CREAR', 'CREAR'), ('TRASLADAR', 'TRASLADAR'), ('LIBERAR', 'LIBERAR')], max_length=20),
        ),
    ]
