# Generated by Django 6.0.3 on 2026-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0006_alter_movimientoextension_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoextension',
            name='ticket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
