# Generated by Django 6.0.3 on 2026-05-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensiones', '0007_alter_movimientoextension_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='ceco',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='codigo_ceco',
        ),
        migrations.AddField(
            model_name='extension',
            name='id_ceco',
            field=models.ForeignKey(blank=True, db_column='id_ceco', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.ceco'),
        ),
        migrations.AddField(
            model_name='extension',
            name='id_codigoceco',
            field=models.ForeignKey(blank=True, db_column='id_codigoceco', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensiones', to='extensiones.codigoceco'),
        ),
    ]
